const POST_TYPE = {
  POST: 1,
  TWEET: 2,
  PAGE: 3
}

const ALLOWED_POST_TYPES = [POST_TYPE.POST, POST_TYPE.TWEET]
const BLOCKED_IMPORT_POST_TYPES = [POST_TYPE.PAGE]

const POST_STATUS = {
  DRAFT: 0,
  PUBLISHED: 1,
  TRASH: 99
}

module.exports = {
  ALLOWED_POST_TYPES,
  BLOCKED_IMPORT_POST_TYPES,
  POST_STATUS,
  POST_TYPE
}