services:
  server:
    container_name: wikimoe-multilingual-server
    build:
      context: .
      dockerfile: Dockerfile
    image: eeg1412/wikimoe-multilingual-server:latest
    environment:
      TZ: Asia/Shanghai
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_HOST_MULTILINGUAL: ${DB_HOST_MULTILINGUAL}
      JSON_LIMIT: ${JSON_LIMIT}
      URLENCODED_LIMIT: ${URLENCODED_LIMIT}
      SOURCE_DOMAIN: ${SOURCE_DOMAIN}
      IP2LOCATION_FILE_NAME: ${IP2LOCATION_FILE_NAME}
      MAX_HISTORYLOGS_SIZE: ${MAX_HISTORYLOGS_SIZE}
    volumes:
      - ./data/wikimoe-multilingual-server/log:/app/log
      - ./data/wikimoe-multilingual-server/ip2location:/app/utils/ip2location
      - ./data/wikimoe-multilingual-server/backups:/app/backups
      - ./data/wikimoe-multilingual-server/cache:/app/cache
      - ./data/wikimoe-multilingual-server/public:/app/public
      - ./data/wikimoe-multilingual-server/ailog:/app/ailog
      - ./data/wikimoe-multilingual-server/secret:/app/secret
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongodb
    networks:
      - wikimoe
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '512M'
        reservations:
          cpus: '0.25'
          memory: '128M'

  mongodb:
    container_name: wikimoe-multilingual-db
    image: mongo:8.2.3-noble
    volumes:
      - ./data/wikimoe-multilingual-db:/data/db
    networks:
      - wikimoe
    restart: unless-stopped

networks:
  wikimoe:
    driver: bridge
